"""Type stubs for _synapse module."""

from typing import List, Union, Optional

class NDArrayPy:
    """Rust-implemented NDArray class."""
    
    def __init__(self, data: List[float], shape: List[int], dtype: Optional[str] = None) -> None: ...
    
    def __add__(self, other: "NDArrayPy") -> "NDArrayPy": ...
    def __mul__(self, other: "NDArrayPy") -> "NDArrayPy": ...
    def __truediv__(self, other: "NDArrayPy") -> "NDArrayPy": ...
    def __repr__(self) -> str: ...
    
    def dot(self, other: "NDArrayPy") -> "NDArrayPy": ...
    def sum(self) -> float: ...
    def sum_axis(self, axis: int) -> "NDArrayPy": ... 